# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0002_auto_20180727_0711")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone"
            ),
        )
    ]
