# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180727_0929'),
        ('main', '0003_auto_20180728_0533'),
    ]

    operations = [
    ]
