# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180730_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
        migrations.AddField(
            model_name='attendance',
            name='teaches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Teaches'),
        ),
    ]
