# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180728_1458'),
        ('main', '0006_auto_20180730_0743'),
    ]

    operations = [
    ]
